" vim:ff=unix ts=4 ss=4

set background=dark

" yank to clipboard
set mouse=i
if has("clipboard")
  set clipboard=unnamed " copy to the system clipboard

  if has("unnamedplus") " X11 support
    set clipboard+=unnamedplus
  endif
endif