# see:
# http://relaxed.ruby.style/
# https://github.com/bbatsov/rubocop/blob/master/manual/cops.md
# https://github.com/bbatsov/rubocop/tree/master/config
# https://raw.githubusercontent.com/bbatsov/rubocop/master/config/enabled.yml
# https://github.com/tootsuite/mastodon/blob/master/.rubocop.yml

AllCops: { DisplayCopNames: true }

AllCops:
  DisplayCopNames: true,
  TargetRubyVersion: 2.3

Lint/UnusedBlockArgument: { Enabled: false }

Metrics/AbcSize: { Max: 20 }
Metrics/ClassLength: { CountComments: false }
Metrics/CyclomaticComplexity: { Max: 10 }
Metrics/MethodLength:
  Max: 10
  CountComments: false
Metrics/ModuleLength: { CountComments: false }

Style/AndOr: { Enabled: false }
Style/ClassAndModuleChildren: { Enabled: false }
Style/DoubleNegation: { Enabled: false }
Style/EmptyLineAfterMagicComment: { Enabled: false }
Style/Encoding: { Enabled: false }
Style/FormatString: { Enabled: false }
Style/IfUnlessModifier: { Enabled: false }
Style/MultilineBlockChain: { Enabled: false }
Style/RedundantReturn: { Enabled: false }
Style/RedundantSelf: { Enabled: false }
Style/Send: { Enabled: true }
Style/TrailingCommaInLiteral: { Enabled: false }